#!/usr/bin/env bash
set -ex

jupyter nbconvert \
  --ExecutePreprocessor.allow_errors=True \
  --ExecutePreprocessor.timeout=-1 \
  --FilesWriter.build_directory=../results \
  --to notebook \
  --execute RegisterToCCF.ipynb \
  --debug

jupyter nbconvert \
  --ExecutePreprocessor.allow_errors=True \
  --ExecutePreprocessor.timeout=-1 \
  --FilesWriter.build_directory=../results \
  --to notebook \
  --execute ApplyTransformToPointSet.ipynb \
  --debug

